### ISSUE TITLE
no probability appeas to be assigned on question bound

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1002]
My slider is as left as it can be , but the graph is cut before the bound (12) and the UI shows that my prediction is 0 close to the bound:
![image](https://github.com/user-attachments/assets/7f54645b-209c-4a7d-8899-8101bd61a942)

[The question](https://www.metaculus.com/questions/3142/by-2030-how-many-people-will-have-ever-landed-on-the-moon/)

**Comment by lsabor** [comment]
Thanks for adding this.
I've added high priority. I suspect it is merely cosmetic and that upon submission, a valid CDF with a greater than 0 difference between the first and second value will be submitted as the prediction. If so, then this is a boundary issue with how PDFs are displayed, and I'll move the priority down to medium.

**Comment by lsabor** [comment]
Investigated.
In a scendario like this (side sliders tucked close to middle and middle slider all the way left):
![image](https://github.com/user-attachments/assets/e88b6850-c385-4114-a732-ecadbc7b02e3)
The first couple values of the submitted CDF are:
```
[0.0,
 0.5378239237269105,
 0.783230179074174,
 0.8952217335990957,
 0.9463454808315099, 
...
]
```
which indicates that >53% of the prediction mass is between the lower bound and `0.5%` of the range above lower bound, and >94% lies in the first `2.5%` of the range.

The PDF (technically a PMF) that is inferred from this prediction looks like:
```
[0.0,
 0.5378239237269105,
 0.24540625534726357,
 0.11199155452492171,
 0.051123747232414196,
...
]
```
Where the first value is the probability mass below lower bound and the `~0.538` is the total probability mass between lower bound and `0.5%` of the range.
If the question resolves to exactly lower bound, the prediction value evaluated would be this `~0.538`, which I think roughly represents the actual desired prediction.

Since this is cosmetic, I'm moving this down to low priority.
When I address this, I'll start by checking if we just fail to drop the preceding `0` when interpreting the pdf.
The second option is that there is a smoothing function applied that assumes a prepended 0.
The third option is that the first value of the pdf is treated as though it is exactly at the location `0.25%` meaning that hovering over the interval `[0%, 0.25%]` doesn't have data and defaults to `0` rather than just not displaying anything or implicitly stretching the pdf data over to the boundary.

Let me know if you have any questions.

**Comment by lsabor** [comment]
seems to have consequences to this question: https://www.metaculus.com/questions/29028/us-state-dept-global-arms-sales-approved-q4-2024/
So bumping back up to high priority
