### ISSUE TITLE
"others" view in group questions not appearing properly for at least one user

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1062]
See the comment thread here, I believe this means the "others" button here isn't showing up properly for them. I was not able to reproduce. https://www.metaculus.com/questions/22445/which-jurisdiction-will-be-the-tipping-point-in-the-2024-us-presidential-election/#comment-202347

![image](https://github.com/user-attachments/assets/194decec-ec78-47a6-bfdb-faa6280b90a5)

**Comment by TemetN** [comment]
![Image of 'others' dropdown issue](https://github.com/user-attachments/assets/7a335695-404f-4dda-839b-f902d0aeff05)

This is what it looks like specifically, you can just see the outline of the window (and the end of a single e) underneath everything else.

**Comment by SylvainChevalier** [comment]
@TemetN what browser/OS are you seeing this on?

**Comment by TemetN** [comment]
@SylvainChevalier Firefox/Windows 11.

**Comment by TemetN** [comment]
Adding another piece of information, since this seem to be the same bug, when I attempt to use the link button in comments, it pops up below the UI as well, like so -

![image](https://github.com/user-attachments/assets/25812cfa-912a-4c18-bf20-cc44e7e72401)

**Comment by ncarazon** [comment]
@TemetN I attempted to reproduce the issue without success, testing across different browsers (Chrome, Edge, Firefox), devices, and Windows versions (10 and 11). Could you please let me know your browser and Windows versions?
Additionally, it’s possible an extension might be causing the issue. Could you check if the bug still occurs in incognito mode?

**Comment by TemetN** [comment]
Windows 11, Firefox. And yes, moment. Yeah, you're right. My bad on this one, turns out it was my script blocker, I hadn't realized there was something new I hadn't whitelisted. Apologies.

**Comment by ncarazon** [comment]
@TemetN Could you please share the specific extension you’re using and your Firefox version?

**Comment by TemetN** [comment]
@ncarazon No Script, and Firefox 132.01. Also after testing it again when you sent this it's even weirder than I thought. I went back, and for some reason the problem recurred. So I whitelisted a bunch of unrelated sites (newsweek and dailycaller since they were linked in the page), and the problem went away. I thought that couldn't make sense, so I reblocked them, and the problem recurred. So I tried unblocking them one at a time, didn't work. I finally unblocked both again, and it fixed it.

As far as I can tell (disclaimer, this may not be it) it appears to occur if I have any scripts blocked from things linked on the page.

**Comment by ncarazon** [comment]
@TemetN thanks for the detailed response! I was able to reproduce the issue, and it turns out it’s indeed related to blocking links in the News Match section. Specifically, NoScript hides object tags when the URL is blocked:

<img width="444" alt="image" src="https://github.com/user-attachments/assets/f8512d88-22e3-4162-9db2-726baddeb4ee">


I switched to using a regular `img` tag, so this shouldn't be the case anymore. The fix is ready for testing on prod.
