### ISSUE TITLE
Add Claude 3.5 Sonnet 2024-10-22 to AIB models proxy

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1105]
## Current behavior
Add Claude 3.5 Sonnet 2024-10-22 to the models available to bot makers who receive credits.
![Screenshot 2024-10-22 at 2 37 17 PM](https://github.com/user-attachments/assets/d4e2289a-7ece-4067-8797-17f7c31a64a5)

## Expected/desired behavior
Describe the behavior you expect or desire to have. Please provide links to mocks and or similar.

**Comment by Tommetaculus** [comment]
@elisescu Not the highest priority, but hopefully easy.

**Comment by jkraybill** [comment]
Can the proxy not just pass-through the value of "model"? It's strange for a proxy to have to keep up-to-date with valid parameter values that we know will continuously change. (I'm now coding against 20241022 so am eager to have the proxy support it.)

**Comment by Tommetaculus** [comment]
Not yet. It is in the dev queue to add 1022.

**Comment by elisescu** [comment]
Added with [this PR](https://github.com/Metaculus/metaculus/pull/1129), and will be deployed soon.

@jkraybill  it's a good point, and ideally that's how it should be. But because models have different pricing/token and we need to account for that, we went for the simplest solution initially, where we manually do it.

Closing for now, but feel free to reopen if you have additional questions/comments.

**Comment by pgodzin** [comment]
@Tommetaculus @elisescu I still see `You don't have an allowance for model <claude-3-5-sonnet-20241022> on <Anthropic>`

**Comment by jkraybill** [comment]
I'm seeing the same error as @pgodzin for both claude-3-5-sonnet-20241022 and claude-3-5-sonnet-latest.

**Comment by Tommetaculus** [comment]
Phil, you now have 34M tokens for 1022.

I will remove the other tokens tomorrow.

**Comment by Tommetaculus** [comment]
Jeremy, you now have 34M tokens to 1022. I'll remove your other tokens
tomorrow.
