### ISSUE TITLE
Total forecasters number is occasionally going down over time in Intel QCup question

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1123]
[This one](https://www.metaculus.com/questions/27995/will-intel-be-dropped-from-the-djia-sept-24/)
For example on September 16 it goes from 53 to 50 and back to 53 again.

**Comment by lsabor** [comment]
Very good spot @nangchrys . The cause was a very subtle issue!

In `get_user_forecast_history`, we were using `bisect_left(start_time)` and `bisect_right(end_time) - 1` to determine which forecasts are active at particular timesteps in order to effeciently calculate the aggregation. This was actually just fine when the timesteps were 1 for 1 with the set of start and end times of the input predictions, but when we minimized the history (so we don't have to calculate 4000 points for instance), we remove some timesteps from the list of timesteps to test.
If a particular forecast is unlucky enough to have both it's start time and end time "minimized" from the considered set of timesteps while a timestep remained during the forecast, then `bisect_right(end_time) - 1` will return 1 lower than it should. This is entirely solved by just using `bisect_left(end_time)` in place.

The great news is that the bug didn't effect non-minimized histories, so scoring wasn't effected by this bug - it was purely graphical.

I'll be merging soon, and will kick off a recalculation of the saved aggregations.

I might add a simple unit test to sanity check my work first, though.

**Comment by lsabor** [comment]
the PR fix: https://github.com/Metaculus/metaculus/pull/1131

**Comment by lsabor** [comment]
clsoing as complete
