### ISSUE TITLE
Can't predict in conditional with closed parent

### ISSUE THREAD

**Issue by nangchrys** [Metaculus/metaculus#1139]
The child is open so I should be able to. Question [here](https://www.metaculus.com/questions/16628/spacex-starship-orbit-in-2023-spacex-mars-mission-by-2030/). I think it functions basically as if it'd closed.

**Comment by SylvainChevalier** [comment]
That is the correct behaviour, and consistent with the [old site](https://old.metaculus.com/questions/16628/conditional-spacex-mars-mission-by-2030/). Conditionals are closed when either the parent or child close/resolve. This behaviour was extensively discussed internally when we made conditionals. We settled on this because it frees forecasters to not have to keep two identical predictions up to date (the child + the remaining non-annulled conditional).

The ui should make that clearer, I'll make a ticket about that.
