### ISSUE TITLE
X axis labels quite broken

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1183]
I don't remember if there's an issue being tracked for this or not, but the axis and labels on this question are very broken and make it impossible to forecast on. I think this should be high priority. <https://www.metaculus.com/questions/28423/change-in-givedirectlys-cost-effectiveness/|https://www.metaculus.com/questions/28423/change-in-givedirectlys-cost-effectiveness/>

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1730310590387749?thread_ts=1730310590.387749&cid=C01Q9AQBVHB)

![image](https://github.com/user-attachments/assets/d4a4d5ec-2e3c-4775-a062-6be02075cf5f)

**Comment by lsabor** [comment]
The source of this problem was that the question somehow got an invalid zero point. It was fixed trivially in the admin panel.

The source is that it turns out some users (skmmcj for instance) don't have the "Logarithmic Scaling" choice when creating this question. It seems like it was automatically checked and they weren't given the option to uncheck it. I'll have to look into it further. But no longer "urgent".
