### ISSUE TITLE
disjoint multiple choice questions: "sum to 100" options not available, forecasts summing to 100 not enforced

### ISSUE THREAD

**Issue by draaglom** [Metaculus/metaculus#1184]
## Current behavior

https://www.metaculus.com/questions/11245
https://www.metaculus.com/questions/19716/power-in-gaza-strip-on-january-1-2025/

- I can submit forecasts that sum to greater than or less than 100%;
- I can no longer see an "automatic sum to 100%" button;

## Expected/desired behavior

- I should not be able to submit a group of forecasts that sums to anything other than 100%;
- I should be able to hit a button to automatically adjust forecasts to sum to 100, as once existed

**Comment by hickman-santini** [comment]
@draaglom although in those two cases the options are mutually exclusive and ~exhaustive (though not strictly), they're both "group" questions. We use group questions instead of multiple choice for cases like these where a new candidate or country could enter the field, so that we can add more.

So although you're right that your forecasts shouldn't sum to more than 100%, we don't enforce this on group questions like we do on multiple-choice questions (we do still have that feature! like [this question](https://www.metaculus.com/questions/29090/highest-risk-posed-by-h5-to-the-us-public-by-jan-1-2026/)).

**Comment by draaglom** [comment]
@hickman-santini whoops, sorry, my mistake! I could've sworn that the election one was multiple choice before, but I guess I remembered wrong.
