### ISSUE TITLE
Search does not work at all on tournaments / projects

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1217]
## Current behavior
Search does not work at all on AI Benchmarking. (It does work for other projects.) Example: When I search "Yankees" I get no results, although there are 8 questions with Yankees in the title.
<img width="840" alt="Screenshot 2024-11-01 at 1 01 29 PM" src="https://github.com/user-attachments/assets/36c483c8-a898-4323-bd37-2f94259a0c15">
<img width="906" alt="Screenshot 2024-11-01 at 1 01 57 PM" src="https://github.com/user-attachments/assets/a5ff630f-f7e4-48a7-a002-a5940fa04aef">

This makes it extremely difficult to manage AI Benchmarking.

**Comment by Tommetaculus** [comment]
@hickman-santini @SylvainChevalier This is high priority for me. Hopefully an easy fix - since search works in other places.

**Comment by draaglom** [comment]
related: #1212

**Comment by Tommetaculus** [comment]
Actually, this work around doesn't work because the "My scoreboard" links don't work correctly.

**Comment by lsabor** [comment]
@Tommetaculus The "My scoreboard" links seem to work correctly for me at this point. Can you double check?

**Comment by lsabor** [comment]
Fixed the problem where unscored contributions weren't linked before. Scored ones still aren't linked. Fixing

**Comment by lsabor** [comment]
I'm unsure about the searching issue, so going to reassign this task at the next developer sync.

**Comment by elisescu** [comment]
@Tommetaculus  can you try again on this tournament? I indexed the questions for that tournament - they were not indexed previously.

**Comment by Tommetaculus** [comment]
It works! Thank you Elis!

**Comment by jkraybill** [comment]
@Tommetaculus @elisescu there definitely is still some type of issues. As an example, I can reliably repro this: https://www.metaculus.com/tournament/aibq4/?order_by=-published_at&search=unemployment

Which should return more than 0 results, since aibq4 has multiple "Will China's youth unemployment rate...."

I feel like I'm intermittently seeing other similar types of issues -- please let me know if you'd like me to file separate issues for specific search issues (I'm thinking there are still a bunch of post-migration issues that could be related to this, so don't want to double-submit known issues.)
