### ISSUE TITLE
404 error on live question in AI Benchmarking

### ISSUE THREAD

**Issue by Tommetaculus** [Metaculus/metaculus#1220]
## Current behavior
When I try to go to this question I get a 404 error: https://www.metaculus.com/questions/28959/
![Screenshot 2024-11-01 at 2 25 45 PM](https://github.com/user-attachments/assets/d82db390-ad2f-4797-8ff1-cd7feff34409)

Perhaps a hint: The top of admin shows no resolution, but there is a resolution time set.

## Expected/desired behavior
Describe the behavior you expect or desire to have. Please provide links to mocks and or similar.

**Comment by Tommetaculus** [comment]
@SylvainChevalier @hickman-santini This feels high priority, as the question has resolved and folks are requesting up to date leaderboard for AI Benchmarking.

**Comment by lsabor** [comment]
This question isn't in AI Benchmarking.
It is only in "Harvard AI Safety Fall 2024"

**Comment by lsabor** [comment]
This was caused by a confusion between Post and Question ids.
The id listed is the correct question id, but not the correct post id, so going to the listed url linked to the post (which does exist and is associated with a different question, that is part of a private tournament).
The correct url would be https://www.metaculus.com/questions/29038/
