### ISSUE TITLE
Graph svg interaction is sometime on top of the fitler menu

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#1338]
Current behavior (video cap):

When I try to filter to e.g. Group and Closed (or Open) at once, or MC and Closed (or Open) at once, it takes me to the question beneath the filter menu:

https://github.com/user-attachments/assets/b93e08dd-086c-43c6-866c-b87131b04537

Those combinations _shouldn't work_, but we should do something like grey out Open and Closed if you already have the "Group" or "Multiple Choice" filter on (and vice versa). There are probably other combos that don't make sense.

**Comment by lsabor** [comment]
I'm confused a little.

(Multiple Choice and Open) or (Multiple Choice and Closed) make just as much sense to me as (Binary and Open). MC are just single questions, so their state is pretty straightforward. (might you be referencing conditionals?)

Group question "openness" / "closedness" is a bit more ambiguous, but at the moment they follow a somewhat reasonable pattern: if any subquestion is open, then the Group is open, if all subquestions are closed, then the Group is closed. I personally think that these filters should be on a question by question basis rather than post by post basis, so if you filter "open" and ANY subquestion is open, then that post gets returned, and if any are "closed", then the post will also get returned. But either way, I do think the filters can apply to group questions (same for conditional, it's just a bit more finicky when it comes to determining status)

I can't reproduce the "takes me to the question beneath the filter menu" issue, though i see it in your video.
Are you using a touch screen or a touchpad on a laptop that might be double clicking accidentally?

**Comment by lsabor** [comment]
Looks like the graph svg interaction is somehow on TOP of the menu.
![image](https://github.com/user-attachments/assets/d0caa170-45b6-4a52-9626-5d99f3d40e59)

Interesting, and probably not a difficult fix (for someone much more talented than me at the front end)

**Comment by SylvainChevalier** [comment]
Can't reproduce either.

**Comment by hickman-santini** [comment]
Alright I'm closing, I guess this got fixed

**Comment by exmateriae** [comment]
@hickman-santini @lsabor this is now happening with the "others" selection in group questions (at least) 
for instance this one: https://www.metaculus.com/questions/27811/total-points-in-24-25-premier-league/
(btw the new way to show the predictions in groups is great!)

**Comment by SylvainChevalier** [comment]
Thanks for reporting @exmateriae. Logged here https://github.com/Metaculus/metaculus/issues/2264.
