### ISSUE TITLE
Authors should have permissions over their questions

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1376]
Quoting from [Slack](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1731425480755719?thread_ts=1731116688.399039&cid=C01Q9AQBVHB):

> Authors should always have access to their question no matter what project it goes in? Is this easy to implement or too complicated, or any risks that come to mind from that?
> In the above thread a partner at Verity could no longer access their draft question because it was moved into the Verity project, where they're not a curator.

**Comment by hlbmtc** [comment]
Authors should have access to their posts regardless of default projects or etc — I’ve just double-checked this logic.
Could it be that they had some sort of “coauthorship” rights which we semi-deprecated in the rewrite?

Because right now we only give exclusive rights to [pashka24](https://www.metaculus.com/accounts/profile/197092/) who is the author of this post

**Comment by SylvainChevalier** [comment]
Thank you for looking into it.
Tested, can't reproduce, closing.
