### ISSUE TITLE
Comment anchor scrolls to the wrong position

### ISSUE THREAD

**Issue by hlbmtc** [Metaculus/metaculus#1402]
## Current behavior
Comment anchor scrolls to the wrong position when we render complex markdown template.
Example: https://www.metaculus.com/notebooks/28734/#comment-215570

## Expected/desired behavior
Scroll after post content load

**Comment by SylvainChevalier** [comment]
Also it scrolls slightly too far and the navbar is over the top of the comment.

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
Linked comments get put at the top of the list. That's quite confusing since it puts them out of their context, doesn't honour the "Recent" sort, and the only clue is the low-salience date.

![image](https://github.com/user-attachments/assets/ff08a02b-d393-46fe-950f-26289ea9da65)

What would be better:
- If the comment is loaded by default on the page, let it in its spot and scroll to it.
- If the comment is not loaded by default (i.e. is beyond the "load more" cutoff), put it below the "load more" button until the right context is loaded.

![image](https://github.com/user-attachments/assets/cb30ac97-cbd5-4bee-8a58-7ec7defabe89)

**Comment by hlbmtc** [comment]
@ncarazon Could you please also take a look key factors as well? 
Steps to replicate:
1. Click on any key factor from the Post body:
<img width="801" alt="image" src="https://github.com/user-attachments/assets/260bbce0-c063-418e-98ff-5cea261fbfa7">
2. Check offset
<img width="926" alt="image" src="https://github.com/user-attachments/assets/2e9a4e3c-bb55-46e7-a3f0-aa9311dc1f6b">

**Comment by ncarazon** [comment]
@hlbmtc Sure, I can take a look at the key factors. Could you provide some context on how these key factors are created? That way, I can test it locally.

Additionally, could you check @SylvainChevalier’s previous comment? Currently, the BE moves the comment to the top of the list when `focus_comment_id` is provided. To enable implementation on the FE, we’ll need to adjust the response structure.

Here’s a rough idea: we could send the comment information separately from the results array when the mentioned parameter is provided. If the comment isn’t included in the results for the current page, we can render it at the end of the list; otherwise, we’ll render it in its actual position. Let me know if this approach makes sense and if it’s feasible to implement, considering sorting and filtering options.

Lastly, I think it would be best to handle this change in a separate ticket, as the original one is focused on comment scrolling.

**Comment by ncarazon** [comment]
Tracking linked comment refactor here: https://github.com/Metaculus/metaculus/issues/1609

**Comment by ncarazon** [comment]
Ready for testing on dev

**Comment by SylvainChevalier** [comment]
lgtm!
