### ISSUE TITLE
In the calibration curves, only include questions past their scheduled resolve date

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#1480]
Since many questions can either resolve Yes-early or No-late, it will look like you have a Yes bias until you reach the time the long questions resolve No.
The solution is to only include questions in calibration once they've reached their scheduled resolve date.
There should be a note to that effect below the calibration curve.
The questions can still be included in the other graphs for now.

**Comment by CodexVeritas** [comment]
Linking pull request: https://github.com/Metaculus/metaculus/pull/1569

**Comment by CodexVeritas** [comment]
Finished the pull request. Ready for review @SylvainChevalier

**Comment by CodexVeritas** [comment]
Technically this issue is solved. Though I think we should explore further avenues with this (I'm not sure if the standard is to keep this issue open, or to make a new issue). 

Things to explore further:
- Make unit tests to triple check calibration curve math
- Explore why the 2024 data is causing a calibration dip and data between 2020 and 2023 does not have this (bots are a suspicious cause)
  - Double check that bots are not included when creating the values in Recency Weighted AggregateForecast table rows
  - Triple check that the bots are in fact filtered out post-AggregateForecast caculation
- Do a data dump of the forecasts in the 20-60% range and see if there are any patterns
- See if removing 'possibly spam' forecasts helps - Filter out the forecasts made by people who have not been on the site longer than 1month or who have not made a comment or that were marked spam or that are inactive (these filters might already be applied)
- Double check that the math for calculating recency weighted forecast is correct
- Make sure that the forecasts used in the calibration curve are the same as the ones used from the global leaderboard

Other useful info:
- Results found thus far and other ideas: https://metaculus.slack.com/archives/C52PD5LUS/p1733276259333379?thread_ts=1731959762.059169&cid=C52PD5LUS
- Molly said to check this out and see if we can redo this analysis: https://forum.effectivealtruism.org/posts/ozPL3mLGShqvjhiaG/some-research-ideas-in-forecasting

**Comment by hickman-santini** [comment]
@CodexVeritas thank you!! I'm going to close this. Can you start a discussion actually? with these notes of things to explore? I want to use discussions more.

**Comment by CodexVeritas** [comment]
Linking the [discussion](https://github.com/Metaculus/metaculus/discussions/1672)
