### ISSUE TITLE
Include "predictors" in `@mention` suggestions

### ISSUE THREAD

**Issue by ryooan** [Metaculus/metaculus#1493]
The new username suggestion tool is great, however it seems @ predictors isn't in the library and that causes issues when trying to tag it, as shown below. Note that only admins should be able to tag @ predictors.

https://github.com/user-attachments/assets/8a333498-3858-40bd-8cac-d97b3e5259de

**Comment by ncarazon** [comment]
@ryooan from your screencast, it seems the predictors option is appearing in the mentions popup:

<img width="264" alt="image" src="https://github.com/user-attachments/assets/f6982960-54de-4115-8357-c2e2d54a7137">

To apply a mention, you’ll need to use Tab, Enter, or a mouse click:

https://github.com/user-attachments/assets/4a416318-bed0-43f8-9b55-6180e33bd947

I assume the issue is that `predictors` is not the first match in the mentions list? If that’s the case, there’s already feedback tracked on a separate ticket to address this: https://github.com/Metaculus/metaculus/issues/538. 

Currently, the app doesn’t filter out this option for non-admin users though. I’ll work on fixing that.

**Comment by ryooan** [comment]
Ah okay thanks @ncarazon !

There is one thing that I think could still be addressed separately, which is that when you hit space I think it should use whatever you typed. The part that was confusing here is I tried to continue on with the sentence because I knew I had the right tag text, but it didn't "release" me from the suggestion feature.

**Comment by ncarazon** [comment]
Deployed a fix to remove the predictors item for non-admin users to dev.

As for the second feature, I suggest moving it to a separate, lower-priority issue. The mentions plugin API doesn’t currently support custom keyboard triggers for selecting markdown, so implementing this functionality would require additional time and effort.

**Comment by SylvainChevalier** [comment]
lgtm
