### ISSUE TITLE
"Resolving soon" filter shouldn't require the question to be open

### ISSUE THREAD

**Issue by George3d6** [Metaculus/metaculus#386]

**Comment by hickman-santini** [comment]
Ok so strictly speaking it doesn't _require_ the question to be open now, but if I deselect the "open" filter when I'm filtering to resolving soon, these are the top questions (already resolved, rather than resolving soon):
![image](https://github.com/user-attachments/assets/14699bdc-cac8-47b2-9685-36cf01d79661)

@hlibowski should I make a separate issue for this?

**Comment by hickman-santini** [comment]
To be clear, I think the desired behavior when you have `order_by=scheduled_resolve_time` without `status=open`, you should see open questions as well as closed, just sorted by scheduled resolve time (soonest first).

**Comment by hickman-santini** [comment]
Looks good on dev now. Below is solely ordering by `order_by=scheduled_resolve_time`. The first questions are all scheduled to resolve today or tomorrow. First open question is [this one](https://dev.metaculus.com/questions/3109/), which is what you'd expect.

![image](https://github.com/user-attachments/assets/829ff9c6-9d87-4094-a710-75ff1b91f476)
