### ISSUE TITLE
New predictions aren't registered immediately under "My Prediction"

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#391]
## Current behavior
When you make a prediction, the "Predict" button is greyed out, but your new prediction isn't registered under "My Prediction" (although it is there when I refresh)
![image](https://github.com/user-attachments/assets/362a22ec-f87c-4e2e-8d27-e8b296099515)
https://beta.metaculus.com/questions/349

## Expected/desired behavior
You'd expect when you click "Predict" to at least see the new prediction under "My Prediction," and ideally get some kind of "update saved" message (although this was probably a design desicion... @SylvainChevalier can you confirm? Fwiw Temet was confused)

Reported by TemetNosce

**Comment by George3d6** [comment]
The backend should support this *but* doing it on the frontend is a bit tricky.

@ncarazon see my implementation in `ForecastMakerBinary` -- I basically use `router.push` with a timestamp (didn't work as a search param for some reason).

I don't think this is ideal but I'm not sure how to do it otherwise without:
1. Using window.location.reload() which is even worse (I think?)
2. Having props propagated from every single forecast maker to the top level post page so that I trigger a refresh there

Will leave the implementation to you in case you have a more elegant solution.

Additionally, I'm curious if we can add some more obvious form of loading when a prediction is being made (maybe the `Predict` / `Save Changes` button gets a spinny circle or something like that)
