### ISSUE TITLE
My predictions are missing from multiple choice timelines

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#400]
The multiple choice timeline doesn't show my predictions.

[www](https://www.metaculus.com/questions/21799/2027-french-presidential-elections/):
![image](https://github.com/user-attachments/assets/7129ad16-1659-4061-aeec-ccb9757d9c7d)

[beta](https://beta.metaculus.com/questions/21799):
![image](https://github.com/user-attachments/assets/2b3be6c2-5b4b-482d-a8c7-d3630ae2ae91)

**Comment by George3d6** [comment]
It looks like this functionality was never implemented for actual multiple choice charts, only groups. BE should be sending the user's forecasts here so it's just a matter of FE implementation

**Comment by ncarazon** [comment]
@George3d6 this was fixed in terms of [this](https://github.com/Metaculus/metaculus/issues/385) issue in the following PR:

https://github.com/Metaculus/metaculus/pull/418

And it seems fixed on dev. How often do we update the beta? Should I mark is as "closed" right away or I should wait for the next beta deploy?
