### ISSUE TITLE
Continuous question feed tiles are missing my prediction

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#401]
The feed tiles for continuous questions should show my prediction pdf when logged in as my account.

[www](https://www.metaculus.com/questions/?search=weak%20ai&order_by=-rank):
![image](https://github.com/user-attachments/assets/a91cade6-6b5b-49a1-9baa-fd58d65b520b)

[beta](https://beta.metaculus.com/questions?forecaster_id=105951&order_by=-weekly_movement&search=weak+ai):
![image](https://github.com/user-attachments/assets/84741e9d-cdce-4eac-aeb0-ad63f72e3112)

**Comment by George3d6** [comment]
I believe this data is being send to the FE and it's just a matter of plotting it.

**Comment by ncarazon** [comment]
@George3d6 

I've refactored the charts to render user predictions without relying on `slider_values`, so we now have user predictions displayed on the feed page. However, there is still one small issue with such questions: the slider in the prediction maker is set to the default position instead of the old prediction. I don't believe we can fix this without fixing the missing data on BE.

**Comment by SylvainChevalier** [comment]
@ncarazon I believe that part should be fixed by #399.
