### ISSUE TITLE
Sorting by "Closing Soon" shows questions that shouldn't be there

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#409]
## Current behavior

https://beta.metaculus.com/questions?order_by=scheduled_close_time&status=open

While these top three say "Closes Jan 4" and other dates in the past, they actually don't close for quite some time, e.g. the children on the top conditional shouldn't close until [2026](https://beta.metaculus.com/questions/6508), I think... although it says "Pending resolution." So I'm confused, but I'm pretty confident that these three questions shouldn't show up when you order by scheduled close time.

![image](https://github.com/user-attachments/assets/5a35bc6d-991e-4773-8c15-a4ea7fe70802)

## Expected/desired behavior

Wouldn't expect these conditionals to appear at the top when sorting by scheduled close time. There's something wrong with their close dates. On prod, we have:

![image](https://github.com/user-attachments/assets/283b26f8-3cf4-421d-922c-cbeea5dc8399)

Reported by TemetNosce

**Comment by George3d6** [comment]
Conditional close dates should be min of close dates for either questions that generated them, and max resolution dates for either -- In this case the conditional does this correctly 

Closing dates and the way they are set, e.g. this question:  https://www.metaculus.com/questions/6508/btc-outperforms-the-us-total-stock-market/ , seems to have a past closing date

The issue here is that during our migration (and during normal operations) closing a parent or child did not close the conditional it belonged to, nor did setting it's scheduled resolution/close time affect those properties for the conditional.

I've now patched this, to see the fix you need to wait until we run the next migration (hopefully tonight) and redeploy to beta

The only issue at hand
