### ISSUE TITLE
More precision when <3% or >97%

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#539]
## Current behavior
When I forecast 0.5<=x<1.5% "my prediction" shows up as 1%.
![image](https://github.com/user-attachments/assets/eef0c87c-d172-4430-a2a9-6c2b13b4438e)

## Expected/desired behavior
Instead of rounding to the nearest integer, for CP and My Prediction, can we keep one sig fig? I'd also like to know what the CP is with more precision when it gets sub-1%.

We don't allow sub-0.1% anyway, so this would just have the effect of preserving one place after the decimal point when forecasts get sub-1%.

Alternatively: Keep one place after the decimal point whenever CP or My Prediction get **>99% or <1%**.

**Comment by nangchrys** [comment]
I think it's better if the increased precision didn't depend on the exact value. I might want to decay my prediction by a specific non-integer amount every month, but if I don't know the previous values with precision, I would have to recalculate that every time. I think there are many users that do this. Plus, I can't track the evolution of my forecasts with detail.

**Comment by SylvainChevalier** [comment]
Hummmm. Yes, let's show more precision but only for the user prediction, not for the CP.

So:
- If the user CP is not a round percentage, show the decimal. E.g. 46.0%→"46%" and 83.6%→"83.6%".
- When the CP value is <3.0% or >97.0%, show the decimal. E.g. "2.3%", "99.6%".
- When the CP value is in 3.0%→97.0%, round to the nearest %. E.g. 24.5%→"25%".

**Comment by lsabor** [comment]
I think that 1 and 2 of sylvain's requests are done.

I don't like 3, and would strongly prefer to just keep it where it is.

So I propose closing this. @SylvainChevalier ?

**Comment by nangchrys** [comment]
![image](https://github.com/user-attachments/assets/ebea787f-461f-4d1b-afa3-045f758df619)

**Comment by lsabor** [comment]
Oh! Aparently not.

**Comment by lsabor** [comment]
predictions do now display with decimal precision now, but all across the range.
Most of the time, if the CP is near the edge of the range (at least for binary), it isn't a decimal because it takes the weighted median user prediction and user predictions not near 0 or 100 tend to be whole percent. I think the precision is thus naturally built into the input of the system, and rounding wouldn't server much purpose except add more conditions to the code.

I'm going to close it now as complete.
