### ISSUE TITLE
"Load more" behavior on comments on the profile page is off

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#599]
Reported by oldwindways:

> When I look at my comments, I do not see any of them populated when the page first loads.
> ![image(15)](https://github.com/user-attachments/assets/1bf3cdb3-5b31-4d0d-8b26-b05b7d174b1e)
> 
> Only after I click "Load more comments" do any appear, and in that case, only 1 shows up.  Clicking "Load more comments" a second time does make 2 more show up, but these are all comments from Sep 9, 2024, so I am confused as to why they did not all load at once.
> 
> Getting a 4th and then eventually 5th comment to load required clicking "Load more comments" multiple times (sometimes clicking it appears to "refresh" the bottom of the page, but no more comments appear).

**Comment by lsabor** [comment]
I figured it out - our default comment feed display only paginates root comments, but in the "all user's comments" section, it shouldn't exclude non-root comments. Users who see "load more" but don't see anything load is because all of the extra loaded comments are branches rather than roots.
Pretty straight forward fix, nearly done implementing.

**Comment by lsabor** [comment]
completed - closing
