### ISSUE TITLE
chips don't appear in feed tiles

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#609]
chips missing in feed tiles in general:
main site:
![image](https://github.com/user-attachments/assets/4c83797f-c6e7-4d4d-b6a4-5c2738bc0d7c)

rewrite:
![image](https://github.com/user-attachments/assets/64a96b5f-ad95-42dc-ac60-465a2ce9f252)

(two minor bugs, question unread is negative? and y axis date labels are crowded)

**Comment by lsabor** [comment]
Also missing Multiple Choice style legend on the right

**Comment by lsabor** [comment]
@hickman-santini deferring to you for priority and assignment

**Comment by hickman-santini** [comment]
1. Chips should appear on the feed tiles
2. Figuring out what's going on with negative questions unread should be high-priority, I'll make a separate issue for that.
3. Can we just remove the y axis label from the feed tiles altogether. I think it's important that the feed look pretty nice.
4. The lines should continue to "now" even if the CP hasn't changed (I assume that's why the green and red lines discontinue). I'm pretty sure we fixed this once before though I can't find the issue now. This seems like it might have a different root than https://github.com/Metaculus/metaculus/issues/612, or no?

Assigning to @hlbmtc to fix (1) and (3). I'll check (4) once that other issue is closed.

**Comment by lsabor** [comment]
@ncarazon Passing back to you.
I've confirmed that the info on the chips do exist in the response:
e.g. for post 13732, including in the feed, has post.projects.tournaments which is a list of tournament objects with chip like properties: e.g. 
```
serialized_data["projects"]["tournament"]
[{'id': 1998, 'type': 'tournament', 'name': '🛰 The Sagan Space Tournament 🛰', 'slug': 'sagan-tournament', 'prize_pool': '5000.00', 'start_date': '2022-11-30T17:00:00Z', 'close_date': '2031-01-05T20:00:00Z', 'meta_description': '', 'is_ongoing': True, 'user_permission': None, 'created_at': '2023-11-08T16:55:29.484707Z', 'edited_at': '2024-03-14T16:06:06.888060Z', 'default_permission': 'forecaster', 'add_posts_to_main_feed': True}]
```

**Comment by lsabor** [comment]
1. should get fixed
2. That was an issue with my local database - so no action needed
3. no strong opinion
4. They shouldn't extent specifically because those are resolved options. They should be truncated and have a resolution diamond there, though.
5. great
