### ISSUE TITLE
Group questions timeline doesn't extend

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#612]
![image](https://github.com/user-attachments/assets/e9c116be-1bd2-477e-bbdc-a866c62284f8)

**Comment by hickman-santini** [comment]
Not quite what we want! Here's two example from www:
![image](https://github.com/user-attachments/assets/227b023a-3a89-4790-a34c-1e90b14a965a)
![image](https://github.com/user-attachments/assets/e237f4ed-ca18-49ef-81b7-3105f6835cdd)

We want the graph to END at the (last) resolution day, rather than continue to "now" such that there's more and more empty space as time goes on. There shouldn't be "now" at all once a question has resolved. Lmk if that makes sense.
![image](https://github.com/user-attachments/assets/fb213763-10ab-41e4-b888-2ca01da1e6f6)
