### ISSUE TITLE
editing continuous question in edit panel doesn't work

### ISSUE THREAD

**Issue by lsabor** [Metaculus/metaculus#958]
editing continuous question in edit panel doesn't work

**Comment by ryooan** [comment]
One thing to note, I think previously when we edited an open continuous question on the front end the range information was intentionally uneditable (because we were never supposed to edit it or it would screw up existing forecasts). Might be worth implementing if it's not too challenging, to avoid potential issues caused by accidental or ignorant edits of the range.
