### ISSUE TITLE
User mention formatting only appears on page reload

### ISSUE THREAD

**Issue by SylvainChevalier** [Metaculus/metaculus#970]
When I type a @username in a comment, it only gets formatted (underline + link) after I reload the page. If this is fixed by #538 then ignore.

Example before reload (the first one is formatted because it was added automatically when replying, see #832):
![image](https://github.com/user-attachments/assets/8807f375-7d00-4b3b-82cc-f4e6e66f9b00)

**Comment by ncarazon** [comment]
@hlbmtc we're currently missing the `mentioned_users` array when creating a comment. Additionally, the response is empty when we edit a comment. Because of this, I had to implement a workaround with a second request to the `/comments` endpoint. Now everything should be working fine, but could you adjust the return data for comment creation/editing so we can avoid redundant requests?

**Comment by SylvainChevalier** [comment]
lgtm
