### ISSUE TITLE
forpol subdomain unable to resolve questions

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#988]
Pavel from the Czech Priorities org:
"We have cooperated with Metaculus on several forecasting projects in the past and we are still using a Metaculus subdomain - <http://forpol.metaculus.com|forpol.metaculus.com>. It seems that the changes done to the main Metaculus platform did not affect the subdomain, but might interfere with it in some way.

Currently, I am unable to resolve any of the questions on the subdomain (there is an endless reloading when attempting to resolve the questions).

I am wondering - could the rewrite might be the explanation for the inability to resolve questions? Also, would it be possible to make the subdomain up-to-date with all the improvements and changes the platform went through in recent days (and months)?

Thanks a lot for your response and have a great day!"

[Slack Message](https://metaculus.slack.com/archives/C01Q9AQBVHB/p1728681334768179)

**Comment by lsabor** [comment]
Looks like this is true of old.metaculus.com as well. Looking into it now.

**Comment by lsabor** [comment]
I think it was just that there were no worker dynos on the site. Those are generally responseible for behind the scene tasks like question resolution and sending emails etc. Since there were none active, none of that got done.
I've turned on 1 celery worker and 1 celery beat schedule worker.

Providing them with an up to date server might be doable, but the current plan is to wait until communities are hammered out, because otherwise we're just increasing our site maintainence by a factor of 2 if we choose to support the forpol subdomain as it's own metaculus instance.

**Comment by lsabor** [comment]
Yup, I'm like 95% sure that was it, becuase some of the questions on the forpol subdomain are now magically resolved.

@hickman-santini can you communicate to them that it should be working now and apologies for the lapse in service. Please recommend them to look over the resolutions that were started because those tasks may have completed now, and if multiple resolution tasks were queued up there is a chance that the "correct" one wasn't the last one to get executed.

I think the basic task here is complete (namely reactivate resolving), so I'll leave it up to you to decide if you want to close this ticket or leave it open until we address bringing their subdomain up into the rewrite version.

**Comment by lsabor** [comment]
My confidence is up to 99%, so I moved this from High to Medium since the big issue is addressed.

**Comment by lsabor** [comment]
Since this hasn't been reported again. Closing as complete
